src/Entity/Player.php
<?php

namespace App\Entity;

use App\Repository\PlayerRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity(repositoryClass: PlayerRepository::class)]
class Player
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nombre = null;

    #[ORM\Column]
    private ?int $nivel = null;

    #[ORM\Column]
    private ?float $experiencia = null;

    #[ORM\Column]
    private ?int $vida_actual = null;

    #[ORM\Column]
    private ?int $vida_maxima = null;

    #[ORM\Column(nullable: true)]
    private ?float $speed = null;

    #[ORM\Column(nullable: true)]
    private ?float $jumpSpeed = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fecha_creacion = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $ultima_conexion = null;

    #[ORM\ManyToOne(inversedBy: 'players')]
    #[ORM\JoinColumn(name: 'games_id', referencedColumnName: 'id')]
    private ?Game $game = null;

    #[ORM\OneToMany(mappedBy: 'player', targetEntity: Sprite::class, cascade: ['persist', 'remove'])]
    private Collection $sprites;

    #[ORM\OneToMany(mappedBy: 'player', targetEntity: UserLevel::class, cascade: ['persist', 'remove'])]
    private Collection $userLevels;

    #[ORM\OneToMany(targetEntity: UserPlayer::class, mappedBy: 'player')]
    private Collection $userPlayers;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $name_sprite = null;
    
    public function __construct()
    {
        $this->sprites = new ArrayCollection();
        $this->userLevels = new ArrayCollection();
        $this->userPlayers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;
        return $this;
    }

    public function getSpeed(): ?float
    {
        return $this->speed;
    }

    public function setSpeed(?float $speed): static
    {
        $this->speed = $speed;
        return $this;
    }

    public function getJumpSpeed(): ?float
    {
        return $this->jumpSpeed;
    }

    public function setJumpSpeed(?float $jumpSpeed): static
    {
        $this->jumpSpeed = $jumpSpeed;
        return $this;
    }

    public function getNivel(): ?int
    {
        return $this->nivel;
    }

    public function setNivel(int $nivel): static
    {
        $this->nivel = $nivel;
        return $this;
    }

    public function getExperiencia(): ?float
    {
        return $this->experiencia;
    }

    public function setExperiencia(float $experiencia): static
    {
        $this->experiencia = $experiencia;
        return $this;
    }

    public function getVidaActual(): ?int
    {
        return $this->vida_actual;
    }

    public function setVidaActual(int $vida_actual): static
    {
        $this->vida_actual = $vida_actual;
        return $this;
    }

    public function getVidaMaxima(): ?int
    {
        return $this->vida_maxima;
    }

    public function setVidaMaxima(int $vida_maxima): static
    {
        $this->vida_maxima = $vida_maxima;
        return $this;
    }

    public function getFechaCreacion(): ?\DateTimeInterface
    {
        return $this->fecha_creacion;
    }

    public function setFechaCreacion(\DateTimeInterface $fecha_creacion): static
    {
        $this->fecha_creacion = $fecha_creacion;
        return $this;
    }

    public function getUltimaConexion(): ?\DateTimeInterface
    {
        return $this->ultima_conexion;
    }

    public function setUltimaConexion(\DateTimeInterface $ultima_conexion): static
    {
        $this->ultima_conexion = $ultima_conexion;
        return $this;
    }
    
    public function getGame(): ?Game
    {
        return $this->game;
    }

    public function setGame(?Game $game): static
    {
        $this->game = $game;
        return $this;
    }

    /**
     * @return Collection<int, Sprite>
     */
    public function getSprites(): Collection
    {
        return $this->sprites;
    }

    public function addSprite(Sprite $sprite): static
    {
        if (!$this->sprites->contains($sprite)) {
            $this->sprites->add($sprite);
            $sprite->setPlayer($this);
        }

        return $this;
    }

    public function removeSprite(Sprite $sprite): static
    {
        if ($this->sprites->removeElement($sprite)) {
            if ($sprite->getPlayer() === $this) {
                $sprite->setPlayer(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return (string) $this->nombre;
    }

    /**
     * @return Collection<int, UserPlayer>
     */
    public function getUserPlayers(): Collection
    {
        return $this->userPlayers;
    }

    public function addUserPlayer(UserPlayer $userPlayer): static
    {
        if (!$this->userPlayers->contains($userPlayer)) {
            $this->userPlayers->add($userPlayer);
            $userPlayer->setPlayer($this);
        }

        return $this;
    }

    public function removeUserPlayer(UserPlayer $userPlayer): static
    {
        if ($this->userPlayers->removeElement($userPlayer)) {
            // set the owning side to null (unless already changed)
            if ($userPlayer->getPlayer() === $this) {
                $userPlayer->setPlayer(null);
            }
        }

        return $this;
    }

    public function getNameSprite(): ?string
    {
        return $this->name_sprite;
    }

    public function setNameSprite(?string $name_sprite): static
    {
        $this->name_sprite = $name_sprite;

        return $this;
    }


}

src/Form/PlayerType.php
<?php

namespace App\Form;

use App\Entity\Player;
use App\Entity\User;
use App\Entity\Game;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\NumberType; // <- para speed y jumpSpeed

class PlayerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre')
            ->add('nivel')
            ->add('experiencia')
            ->add('vida_actual')
            ->add('vida_maxima')
            ->add('speed', NumberType::class, [
                'required' => false,
                'scale' => 2, // permite decimales si quieres
            ])
            ->add('jumpSpeed', NumberType::class, [
                'required' => false,
                'scale' => 2,
            ])
            ->add('name_sprite')
            ->add('fecha_creacion', DateTimeType::class, [
                'widget' => 'single_text',
            ])
            ->add('ultima_conexion', DateTimeType::class, [
                'widget' => 'single_text',
            ])
            ->add('game', EntityType::class, [
                'class' => Game::class,
                'choice_label' => 'nombre',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Player::class,
        ]);
    }
}

src/Controller/PlayerController.php
<?php

namespace App\Controller;

use App\Entity\Player;
use App\Form\PlayerType;
use App\Repository\PlayerRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/player')]
class PlayerController extends AbstractController
{
    #[Route('/', name: 'app_player_index', methods: ['GET'])]
    public function index(PlayerRepository $playerRepository): Response
    {
        return $this->render('player/index.html.twig', [
            'players' => $playerRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_player_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $player = new Player();
        $form = $this->createForm(PlayerType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($player);
            $entityManager->flush();

            return $this->redirectToRoute('app_player_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('player/new.html.twig', [
            'player' => $player,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_player_show', methods: ['GET'])]
    public function show(Player $player): Response
    {
        return $this->render('player/show.html.twig', [
            'player' => $player,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_player_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Player $player, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PlayerType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_player_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('player/edit.html.twig', [
            'player' => $player,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_player_delete', methods: ['POST'])]
    public function delete(Request $request, Player $player, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$player->getId(), $request->request->get('_token'))) {
            $entityManager->remove($player);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_player_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/player/_delete_form.html.twig
<form method="post" action="{{ path('app_player_delete', {'id': player.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ player.id) }}">
    <button class="btn">Delete</button>
</form>

templates/player/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Player{% endblock %}

{% block body %}
    <h1>Edit Player</h1>

    {{ include('player/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_player_index') }}">back to list</a>

    {{ include('player/_delete_form.html.twig') }}
{% endblock %}

templates/player/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Player index{% endblock %}

{% block body %}
    <h1>Player index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Nivel</th>
                <th>name_sprite</th>
                <th>Experiencia</th>
                <th>Vida_actual</th>
                <th>Vida_maxima</th>
                <th>Velocidad</th>
                <th>Fuerza de salto</th>
                <th>Fecha_creacion</th>
                <th>Ultima_conexion</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for player in players %}
            <tr>
                <td>{{ player.id }}</td>
                <td>{{ player.nombre }}</td>
                <td>{{ player.nivel }}</td>
                <td>{{ player.nameSprite  }}</td>
                <td>{{ player.experiencia }}</td>
                <td>{{ player.vidaActual }}</td>
                <td>{{ player.vidaMaxima }}</td>
                <td>{{ player.speed }}</td>
                <td>{{ player.jumpSpeed }}</td>
                <td>{{ player.fechaCreacion ? player.fechaCreacion|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ player.ultimaConexion ? player.ultimaConexion|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_player_show', {'id': player.id}) }}">show</a>
                    <a href="{{ path('app_player_edit', {'id': player.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_player_new') }}">Create new</a>
    <a href="{{ path('app_formularios') }}">Volver al inicio</a>
{% endblock %}

templates/player/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Player{% endblock %}

{% block body %}
    <h1>Create new Player</h1>

    {{ include('player/_form.html.twig') }}

    <a href="{{ path('app_player_index') }}">back to list</a>
{% endblock %}

templates/player/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Player{% endblock %}

{% block body %}
    <h1>Player</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ player.id }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ player.nombre }}</td>
            </tr>
            <tr>
                <th>Nivel</th>
                <td>{{ player.nivel }}</td>
            </tr>
            <tr>
                <th>Experiencia</th>
                <td>{{ player.experiencia }}</td>
            </tr>
            <tr>
                <th>Vida_actual</th>
                <td>{{ player.vidaActual }}</td>
            </tr>
            <tr>
                <th>Vida_maxima</th>
                <td>{{ player.vidaMaxima }}</td>
            </tr>
            <tr>
                <th>Fecha_creacion</th>
                <td>{{ player.fechaCreacion ? player.fechaCreacion|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Ultima_conexion</th>
                <td>{{ player.ultimaConexion ? player.ultimaConexion|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_player_index') }}">back to list</a>

    <a href="{{ path('app_player_edit', {'id': player.id}) }}">edit</a>

    {{ include('player/_delete_form.html.twig') }}
{% endblock %}