src/Entity/Score.php
<?php

namespace App\Entity;

use App\Repository\ScoreRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Player;
use App\Entity\Saves;

#[ORM\Entity(repositoryClass: ScoreRepository::class)]
class Score
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Player::class, inversedBy: 'scores')]
    private ?Player $player = null;

    #[ORM\ManyToOne(targetEntity: Saves::class, inversedBy: 'scores')]
    private ?Saves $saves = null;

    #[ORM\Column]
    private ?int $puntos = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fecha_guardado = null;

    #[ORM\ManyToOne(inversedBy: 'scores')]
    private ?Game $game = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPlayer(): ?Player
    {
        return $this->player;
    }

    public function setPlayer(?Player $player): static
    {
        $this->player = $player;
        return $this;
    }

    public function getSaves(): ?Saves
    {
        return $this->saves;
    }

    public function setSaves(?Saves $saves): static
    {
        $this->saves = $saves;
        return $this;
    }

    public function getPuntos(): ?int
    {
        return $this->puntos;
    }

    public function setPuntos(int $puntos): static
    {
        $this->puntos = $puntos;
        return $this;
    }

    public function getFechaGuardado(): ?\DateTimeInterface
    {
        return $this->fecha_guardado;
    }

    public function setFechaGuardado(\DateTimeInterface $fecha_guardado): static
    {
        $this->fecha_guardado = $fecha_guardado;
        return $this;
    }

    public function getGame(): ?Game
    {
        return $this->game;
    }

    public function setGame(?Game $game): static
    {
        $this->game = $game;
        return $this;
    }
}

src/Form/ScoreType.php
<?php

namespace App\Form;

use App\Entity\Score;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ScoreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('puntos')
            ->add('fecha_guardado')
            ->add('user')
            ->add('saves')
            ->add('game')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Score::class,
        ]);
    }
}

src/Controller/ScoreController.php
<?php

namespace App\Controller;

use App\Entity\Score;
use App\Form\ScoreType;
use App\Repository\ScoreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/score')]
class ScoreController extends AbstractController
{
    #[Route('/', name: 'app_score_index', methods: ['GET'])]
    public function index(ScoreRepository $scoreRepository): Response
    {
        return $this->render('score/index.html.twig', [
            'scores' => $scoreRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_score_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $score = new Score();
        $form = $this->createForm(ScoreType::class, $score);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($score);
            $entityManager->flush();

            return $this->redirectToRoute('app_score_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('score/new.html.twig', [
            'score' => $score,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_score_show', methods: ['GET'])]
    public function show(Score $score): Response
    {
        return $this->render('score/show.html.twig', [
            'score' => $score,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_score_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Score $score, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ScoreType::class, $score);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_score_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('score/edit.html.twig', [
            'score' => $score,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_score_delete', methods: ['POST'])]
    public function delete(Request $request, Score $score, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$score->getId(), $request->request->get('_token'))) {
            $entityManager->remove($score);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_score_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/score/_delete_form.html.twig
<form method="post" action="{{ path('app_score_delete', {'id': score.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ score.id) }}">
    <button class="btn">Delete</button>
</form>

templates/score/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Score{% endblock %}

{% block body %}
    <h1>Edit Score</h1>

    {{ include('score/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_score_index') }}">back to list</a>

    {{ include('score/_delete_form.html.twig') }}
{% endblock %}

templates/score/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Score index{% endblock %}

{% block body %}
    <h1>Score index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Player</th>
                <th>saves</th>
                <th>Game</th>
                <th>Puntos</th>
                <th>Fecha_guardado</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for score in scores %}
            <tr>
                <td>{{ score.id }}</td>
                <td>{{ score.player }}</td>
                <td>{{ score.saves }}</td>
                <td>{{ score.game }}</td>
                <td>{{ score.puntos }}</td>
                <td>{{ score.fechaGuardado ? score.fechaGuardado|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_score_show', {'id': score.id}) }}">show</a>
                    <a href="{{ path('app_score_edit', {'id': score.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_score_new') }}">Create new</a>
    <a href="{{ path('app_formularios') }}">Volver al inicio</a>
{% endblock %}

templates/score/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Score{% endblock %}

{% block body %}
    <h1>Create new Score</h1>

    {{ include('score/_form.html.twig') }}

    <a href="{{ path('app_score_index') }}">back to list</a>
{% endblock %}

templates/score/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Score{% endblock %}

{% block body %}
    <h1>Score</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ score.id }}</td>
            </tr>
            <tr>
                <th>Puntos</th>
                <td>{{ score.puntos }}</td>
            </tr>
            <tr>
                <th>Fecha_guardado</th>
                <td>{{ score.fechaGuardado ? score.fechaGuardado|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_score_index') }}">back to list</a>

    <a href="{{ path('app_score_edit', {'id': score.id}) }}">edit</a>

    {{ include('score/_delete_form.html.twig') }}
{% endblock %}